/*Erik Gonzalez
CO SCI 575
SumOfRandomNumbers.cpp
This program that asks a student to calculate the sum of three random numbers generated by the computer in a range of 15 - 40.  */
#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main()
{
	int randNum1, randNum2, randNum3;
	unsigned int seed;
	int sum, userSum;

	seed = time(0);
	srand(seed);
	//Randomization and calculating the sum of the three numbers
	randNum1 = rand() % 25 + 15;
	randNum2 = rand() % 25 + 15;
	randNum3 = rand() % 25 + 15;
	sum = randNum1 + randNum2 + randNum3;
	//Input
	cout << "What is the sum of the following three random numbers?" << endl;
	cout << "Total: " << randNum1 << " + " << randNum2 << " + " << randNum3 << " =? ";
	cin >> userSum;
	//Output
	if (userSum == sum)
		cout << "Congratulations! You are correct! " << endl;
	else
	{
		cout << "Your answer is wrong." << endl;
		cout << "Total should be: " << sum << endl;
	}

	system("Pause");
	return 0;

}
